# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-11 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200911_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
